version: '3.8'

services:
  mongo-clientes:
    image: mongo:6.0
    container_name: mongo-clientes
    ports:
      - "27017:27017"
    command: ["mongod", "--bind_ip", "0.0.0.0"]
    volumes:
      - mongo-data:/data/db
      - ./src/main/resources/init-scripts:/docker-entrypoint-initdb.d:ro  # Mapeando corretamente o diretório de scripts
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: techfood-clientes
    restart: always  # Reinicia o container automaticamente em falhas
    networks:
      - techfood-net

  app:
    container_name: techfood-clientes-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mongo-clientes  # Aguarda o MongoDB estar pronto antes de iniciar o app
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATA_MONGODB_URI: mongodb://admin:password@mongo-clientes:27017/techfood-clientes?authSource=admin
    restart: always  # Reinicia o container automaticamente em falhas
    networks:
      - techfood-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  techfood-net:
    driver: bridge

volumes:
  mongo-data:
