version: '3.8'

services:
  mongo-clientes:
    image: mongo:6.0
    container_name: mongo-clientes
    ports:
      - "27017:27017"
    networks:
      - techfood-network
    volumes:
      - mongo-data:/data/db
      - ./src/main/resources/init-scripts:/docker-entrypoint-initdb.d:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: techfood-clientes
    restart: always

  techfood-clientes:
    container_name: techfood-clientes-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mongo-clientes
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:password@mongo-clientes:27017/techfood-clientes?authSource=admin
    restart: always
    networks:
      - techfood-network

networks:
  techfood-network:
    external: true

volumes:
  mongo-data:
