server:
  port: 8081

spring:
  application:
    name: techfood-clientes

  cloud:
    config:
      enabled: false

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

  data:
    mongodb:
      # Docker
      # uri: mongodb://admin:password@mongo-clientes:27017/techfood-clientes?authSource=admin&uuidRepresentation=standard
      # localhost
      uri: mongodb://admin:password@localhost:27017/techfood-clientes?authSource=admin&uuidRepresentation=standard
      database: techfood-clientes
      uuid-representation: standard
      connection-timeout: 60000  # Set a higher timeout value (in ms)
      socket-timeout: 60000       # Set socket timeout value (in ms)

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    com.mongodb: DEBUG





