apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: techfood-clientes
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/data/mongodb  # Certifique-se de que o host permite a gravação nesse caminho
