apiVersion: v1
kind: Service
metadata:
  name: techfood-clientes-app
  namespace: techfood-clientes
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: techfood-clientes-app
